-- Supabase SQL Editor에 복사하여 붙여넣고 실행(Run)하세요.
--이 쿼리는 'saved_shorts' 테이블을 생성하고, Row Level Security(RLS) 규칙을 비활성화하거나 누구든 읽고 쓸 수 있도록 공개 규칙을 설정합니다.

-- 1. 테이블 생성
CREATE TABLE IF NOT EXISTS public.saved_shorts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    keyword text DEFAULT '기타'::text NOT NULL,
    platform text DEFAULT 'Other'::text NOT NULL,
    title text NOT NULL,
    video_url text NOT NULL UNIQUE,
    thumbnail_url text DEFAULT ''::text,
    view_count text DEFAULT '0'::text NOT NULL
);

-- 2. Row Level Security (RLS) 설정 (개발용 간편 접근 허용)
-- 누구나 이 테이블에 데이터를 삽입, 조회, 삭제할 수 있도록 RLS를 비활성화하거나 PUBLIC 익명 정책을 추가합니다.
ALTER TABLE public.saved_shorts DISABLE ROW LEVEL SECURITY;

-- 혹은 RLS를 활성화하고 전체 허용 정책을 사용하려면 아래 주석을 해제하세요:
-- ALTER TABLE public.saved_shorts ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow public read" ON public.saved_shorts FOR SELECT USING (true);
-- CREATE POLICY "Allow public insert" ON public.saved_shorts FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Allow public delete" ON public.saved_shorts FOR DELETE USING (true);
